/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FlowBalanceImport } from './routes/flow-balance'
import { Route as IndexImport } from './routes/index'
import { Route as FormIdImport } from './routes/form/$id'

// Create/Update Routes

const FlowBalanceRoute = FlowBalanceImport.update({
  id: '/flow-balance',
  path: '/flow-balance',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormIdRoute = FormIdImport.update({
  id: '/form/$id',
  path: '/form/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/flow-balance': {
      id: '/flow-balance'
      path: '/flow-balance'
      fullPath: '/flow-balance'
      preLoaderRoute: typeof FlowBalanceImport
      parentRoute: typeof rootRoute
    }
    '/form/$id': {
      id: '/form/$id'
      path: '/form/$id'
      fullPath: '/form/$id'
      preLoaderRoute: typeof FormIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flow-balance': typeof FlowBalanceRoute
  '/form/$id': typeof FormIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flow-balance': typeof FlowBalanceRoute
  '/form/$id': typeof FormIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/flow-balance': typeof FlowBalanceRoute
  '/form/$id': typeof FormIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flow-balance' | '/form/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flow-balance' | '/form/$id'
  id: '__root__' | '/' | '/flow-balance' | '/form/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowBalanceRoute: typeof FlowBalanceRoute
  FormIdRoute: typeof FormIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowBalanceRoute: FlowBalanceRoute,
  FormIdRoute: FormIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flow-balance",
        "/form/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/flow-balance": {
      "filePath": "flow-balance.tsx"
    },
    "/form/$id": {
      "filePath": "form/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
